dcdemo:
- service: example-chart
  namespace: 'pf'
  syncWave: "0"
  repo: 'https://github.com/himanshujaindev/example-chart.git'
  targetRevision: 'v5'
  path: 'chart'
  valueFiles:
  - 'custom/dev.yaml'
