dcdemo:
  name: 'test-eks'
  cluster_url: 'https://kubernetes.default.svc'
  apps:
    example-chart:
      namespace: 'pf'
      valueFiles:
        - 'custom/dev.yaml'
      syncWave: "0"
      path: "chart"
      repo: 'https://github.com/himanshujaindev/example-chart.git'
