dcdemo: []
  # - service: example-chart
  #   namespace: 'pf'
  #   syncWave: "0"
  #   repo: 'https://github.com/himanshujaindev/example-chart.git'
  #   targetRevision: 'main'
  #   path: 'chart'
  #   valueFiles:
  #   - 'custom/dev.yaml'