configs:
  cm:
    globalProjects: |-
      - labelSelector:
          matchExpressions:
            - key: argocd.argoproj.io/project-inherit
              operator: In
              values:
                - global
        projectName: global
redis-ha:
  enabled: false
applicationSet:
  replicas: 1
repoServer:
  replicas: 1
server:
  replicas: 1
  resources:
     limits:
       cpu: 50m
       memory: 128Mi
     requests:
       cpu: 10m
       memory: 64Mi
