apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
{{- $parameters := .Files.Get "custom/dcdemo.yaml" | fromYaml }}
{{- $versions := .Files.Get "versions/dcdemo.yaml" | fromYaml }}
{{- $name := $parameters.dcdemo.name }}
{{- $cluster_url := $parameters.dcdemo.cluster_url }}

metadata:
  name: {{ $name }}
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
      {{- range $app, $value := (merge $parameters.dcdemo.apps $versions.dcdemo.apps) }}
          - service: "{{ $app }}"
            namespace: "{{ $value.namespace }}"
            syncWave: "{{ $value.syncWave }}"
            repo: "{{ $value.repo }}"
            path: "{{ $value.path }}"
            valueFiles:
          {{- range $value.valueFiles }}
              - {{ . | quote }}
          {{- end }}
            targetRevision: {{ $value.targetRevision }}
            valueOverride:
          {{- range $value.valueOverride }}
            - name: '{{ .name }}'
              value: '{{ .value }}'
          {{- end }}
      {{- end }}
  template:
    metadata:
      name: '{{ $name }}-{{`{{.service}}`}}'
      labels:
        environment: 'dev'
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: false
      project: default
      destination:
        server: "{{ $cluster_url }}"
        namespace: '{{`{{.namespace}}`}}'
  templatePatch: |
    {{`{{ if ne .syncWave ""}}`}}
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{.syncWave}}`}}'
    {{`{{ end -}}`}}
    spec:
      sources:
        - repoURL: '{{`{{.repo}}`}}'
          targetRevision: '{{ `{{.targetRevision}}` }}'
          path: '{{`{{.path}}`}}'
          helm:
            releaseName: '{{`{{.service}}`}}'
            valueFiles:
            {{`{{ range .valueFiles -}}`}}
            - '{{`{{.}}`}}'
            {{`{{ end }}`}}
            parameters:
            {{`{{ range .valueOverride -}}`}}
            - name: '{{`{{.name}}`}}'
              value: '{{`{{.value}}`}}'
            {{`{{ end }}`}}