apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wxcc-platform-dcdemo
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      {{- $dcdemoVar := .Files.Get "custom/dcdemo.yaml" | fromYaml }}
      {{- range $dcdemoVar.dcdemo }}
        - service: "{{ .service }}"
          namespace: "{{ .namespace }}"
          valueFiles:
          {{- range .valueFiles }}
          - {{ . | quote }}
          {{- end }}
          syncWave: "{{ .syncWave }}"
          repo: "{{ .repo }}"
          path: "{{ .path }}"
          targetRevision: "{{ .targetRevision }}"
      {{- end }}
  template:
    metadata:
      name: '{{`{{.service}}`}}'
    labels:
      test: app
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: false
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{`{{.namespace}}`}}'
  templatePatch: |
    {{`{{ if ne .syncWave ""}}`}}
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{.syncWave}}`}}'
    {{`{{ end -}}`}}
    spec:
      sources:
        - repoURL: '{{`{{.repo}}`}}'
          targetRevision: '{{ `{{.targetRevision}}` }}'
          path: '{{`{{.path}}`}}'
          helm:
            releaseName: '{{`{{.service}}`}}'
            valueFiles:
            {{`{{ range .valueFiles -}}`}}
            - '{{`{{.}}`}}'
            {{`{{ end }}`}}