apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/himanshujaindev/argocd.git
    targetRevision: main
    path: src/app-config/app1

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # syncPolicy: {}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
        - Validate=false
        - ApplyOutOfSyncOnly=false
        - RespectIgnoreDifferences=false
