apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/himanshujaindev/argocd.git
    targetRevision: main
    path: src/app-config/app1

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: false
    syncOptions:
        - Validate=true
        - ApplyOutOfSyncOnly=true
        - RespectIgnoreDifferences=true
