apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/himanshujaindev/argocd.git
    targetRevision: main
    path: self-manage/argo/charts/argo-cd
    helm:
      version: v3
      valueFiles:
      - values.yaml
      - custom/local.yaml
      parameters:
      - name: namespace
        value: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
